examenfinal/examenfinal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from miapp import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.index, name = "index"),
    path('personas/', views.personas, name = "personas"),
    path('agregar_persona/', views.agregar_persona, name='agregar_persona'),
    path('eliminar_persona/<int:id>/', views.eliminar_persona, name="eliminar_persona"),
    path('editar_persona/<int:id>/', views.editar_persona, name='editar_persona'),
]

examenfinal/miapp/models.py
from django.db import models

# Create your models here.
class Huertas_Persona(models.Model):
    SEXO = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    ]
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    sexo = models.CharField(max_length=1, choices=SEXO)
    fecha_registro = models.DateTimeField(auto_now_add=True)

examenfinal/miapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Huertas_Persona

# Create your views here.
def index(request):
    return render(request, 'index.html')


def agregar_persona(request):
    if request.method == 'POST':
        nombre = request.POST['nombre']
        apellidos = request.POST['apellidos']
        sexo = request.POST['sexo']
        persona = Huertas_Persona(nombre=nombre, apellidos=apellidos, sexo=sexo)
        persona.save()
        messages.success(request, 'La persona ha sido agregada con éxito.')
        return redirect('personas')
    return render(request, 'agregar_persona.html')

def editar_persona(request, id):
    persona = get_object_or_404(Huertas_Persona, id=id)
    if request.method == 'POST':
        persona.nombre = request.POST['nombre']
        persona.apellidos = request.POST['apellidos']
        persona.sexo = request.POST['sexo']
        persona.save()
        messages.success(request, 'La persona ha sido actualizada con éxito.')
        return redirect('personas')
    return render(request, 'editar_persona.html', {'persona': persona})

def personas(request):
    personas = Huertas_Persona.objects.all()
    return render(request, 'personas.html', {'personas': personas})

def eliminar_persona(request, id):
    persona = get_object_or_404(Huertas_PersonaPersona, id=id)
    persona.delete()
    messages.success(request, 'La persona ha sido eliminada con éxito.')
    return redirect('personas')

examenfinal/miapp/templates/agregar_persona.html
{% extends 'layout.html' %}

{% block content %}
<h1>Agregar Persona</h1>
<form action="{% url 'agregar_persona' %}" method="post">
    {% csrf_token %}
    <label for="nombre">Nombre:</label>
    <input type="text" id="nombre" name="nombre" required>
    <br>
    <label for="apellidos">Apellidos:</label>
    <input type="text" id="apellidos" name="apellidos" required>
    <br>
    <label for="sexo">Sexo:</label>
    <select id="sexo" name="sexo">
        <option value="M">Masculino</option>
        <option value="F">Femenino</option>
    </select>
    <br>
    <button type="submit">Guardar Persona</button>
</form>
{% endblock %}

examenfinal/miapp/templates/editar_persona.html
{% extends 'layout.html' %}

{% block content %}
<h1>Editar Persona</h1>
<form action="{% url 'editar_persona' persona.id %}" method="post">
    {% csrf_token %}
    <label for="nombre">Nombre:</label>
    <input type="text" id="nombre" name="nombre" value="{{ persona.nombre }}" required>
    <br>
    <label for="apellidos">Apellidos:</label>
    <input type="text" id="apellidos" name="apellidos" value="{{ persona.apellidos }}" required>
    <br>
    <label for="sexo">Sexo:</label>
    <select id="sexo" name="sexo">
        <option value="M" {% if persona.sexo == 'M' %}selected{% endif %}>Masculino</option>
        <option value="F" {% if persona.sexo == 'F' %}selected{% endif %}>Femenino</option>
    </select>
    <br>
    <button type="submit">Guardar Cambios</button>
</form>
{% endblock %}

examenfinal/miapp/templates/index.html
{% extends 'layout.html' %}

{% block content %}

{% endblock %}

examenfinal/miapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.cdnfonts.com/css/gt-america-trial" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" href="{% static '/css/styles.css' %}">

    <title>Abstract Clone</title>
</head>

<body>
    <header class="topbar">
        <div class="topbar-inner">
            <img src="{% static 'img/Untels_01.png' %}" viewBox="0 0 32 32"><defs><style>.cls-1{fill:#fff}</style></defs><g id="computer"><path class="cls-1" d="M27.14 3H4.86A2.86 2.86 0 0 0 2 5.86V8a1 1 0 0 0 2 0V5.86A.87.87 0 0 1 4.86 5h22.28a.87.87 0 0 1 .86.86v15.28a.87.87 0 0 1-.86.86H4.86a.87.87 0 0 1-.86-.86V20h21a1 1 0 0 0 0-2H4v-6a1 1 0 0 0-2 0v9.14A2.86 2.86 0 0 0 4.86 24h7.22a8.7 8.7 0 0 1-.08 1.84 8.53 8.53 0 0 1-.63 2.16H10a1 1 0 0 0 0 2h12a1 1 0 0 0 0-2h-1.37a8.53 8.53 0 0 1-.63-2.16 8.7 8.7 0 0 1-.08-1.84h7.22A2.86 2.86 0 0 0 30 21.14V5.86A2.86 2.86 0 0 0 27.14 3zM18 26.16a10.57 10.57 0 0 0 .48 1.84h-5a10.57 10.57 0 0 0 .52-1.84 11.19 11.19 0 0 0 .11-2.16h3.78a11.19 11.19 0 0 0 .11 2.16z"/><path class="cls-1" d="M11.25 15.66A1 1 0 0 0 12 16a1 1 0 0 0 .66-.25l8-7a1 1 0 1 0-1.32-1.5l-8 7a1 1 0 0 0-.09 1.41zM13 8a1 1 0 0 0-1-1 1 1 0 1 0 1 1zM20 14a1 1 0 1 0 1 1 1 1 0 0 0-1-1z"/></g></svg>
            
            <a class="topbar-inner__helpcenter" href="#"></a>
            <a class="topbar-inner__search" href="#">

                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                    style="fill: rgb(255, 255, 255);">
                    <path
                        d="M10 18a7.952 7.952 0 0 0 4.897-1.688l4.396 4.396 1.414-1.414-4.396-4.396A7.952 7.952 0 0 0 18 10c0-4.411-3.589-8-8-8s-8 3.589-8 8 3.589 8 8 8zm0-14c3.309 0 6 2.691 6 6s-2.691 6-6 6-6-2.691-6-6 2.691-6 6-6z">
                    </path>
                </svg>

            </a>
            <a class="topbar-inner__signin" href="{% url 'personas' %}">Personas</a>
            <a class="topbar-inner__signin" href="{% url 'agregar_persona' %}">Agregar Personas</a>
        </div>
    </header>
    <main>
        {% block content %}


        {% endblock %}
    </main>
    <footer class="footer">
        <div class="footer-inner">
            <div class="footer__column">
                <h3>Integrantes</h3>
                <a href="#">Huertas</a>
            </div>
            <div class="footer__column">
                <h3>Profesora</h3>
                <a href="#">Flor Cerdan</a>
            </div>
            
            <div class="footer__column footer__column-copyright">
                
                
                <p>© Copyright 2024</p>
                <p>All rights reserved</p>
            </div>
        </div>
    </footer>
</body>

</html>

examenfinal/miapp/templates/personas.html
{% extends 'layout.html' %}

{% block content %}
<h1>Listado de personas</h1>
<a href="{% url 'agregar_persona' %}" class="btn btn-add">Agregar Persona</a>
<ul>
    {% for persona in personas %}
        <li>Nombre: {{ persona.nombre }} {{ persona.apellidos }} - 
            Sexo: {{ persona.get_sexo_display }} - 
            Fecha de registro: {{ persona.fecha_registro }} - 
            <a href="{% url 'editar_persona' id=persona.id %}" class="btn btn-edit">Editar</a>
            <a href="{% url 'eliminar_persona' id=persona.id %}" class="btn btn-delete">Eliminar</a>
        </li>
    {% endfor %}
</ul>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% endblock %}